name: CI Build and Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        java-version: [17, 21]
    
    steps:
    - name: 检出代码
      uses: actions/checkout@v4
    
    - name: 设置 JDK ${{ matrix.java-version }}
      uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.java-version }}
        distribution: 'temurin'
        cache: maven
    
    - name: 缓存 Maven 依赖
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    
    - name: 构建项目
      run: mvn clean compile -B
      env:
        CI: true
    
    - name: 运行单元测试（自动排除MySQL和PostgreSQL测试）
      run: mvn test -B
      env:
        CI: true
        # 只使用H2内存数据库进行测试
        DB_TYPE: h2
    
    - name: 打包
      run: mvn package -DskipTests -B
    
    - name: 上传测试报告
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-reports-java-${{ matrix.java-version }}
        path: |
          **/target/surefire-reports/
          **/target/test-classes/
        retention-days: 7
