name: Performance Tests

on:
  schedule:
    - cron: '0 3 * * 0'  # 每周日凌晨3点运行
  workflow_dispatch:

jobs:
  performance-test:
    name: Performance Benchmark
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
        
    - name: Build project
      run: mvn clean package -DskipTests=true
      env:
        CI: true
      
    - name: Start application
      run: |
        java -jar target/vxcore-example-*.jar &
        sleep 15
        
    - name: Install Apache Bench
      run: sudo apt-get update && sudo apt-get install -y apache2-utils
        
    - name: Run HTTP performance test
      run: |
        ab -n 10000 -c 100 http://localhost:8080/api/hello?name=Test > http-performance.txt
        
    - name: Run database performance test
      run: |
        ab -n 5000 -c 50 http://localhost:8080/api/users > db-performance.txt
        
    - name: Stop application
      run: pkill -f "vxcore-example"
      
    - name: Upload performance results
      uses: actions/upload-artifact@v3
      with:
        name: performance-results
        path: |
          http-performance.txt
          db-performance.txt
        retention-days: 30
        
    - name: Comment performance results
      if: github.event_name == 'workflow_dispatch'
      uses: actions/github-script@v6
      with:
        script: |
          const fs = require('fs');
          const httpPerf = fs.readFileSync('http-performance.txt', 'utf8');
          const dbPerf = fs.readFileSync('db-performance.txt', 'utf8');
          
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: `## Performance Test Results
            
            ### HTTP Performance
            \`\`\`
            ${httpPerf}
            \`\`\`
            
            ### Database Performance
            \`\`\`
            ${dbPerf}
            \`\`\`
            `
          });
